import pyautogui

pyautogui.press("win")
pyautogui.sleep(1)
pyautogui.write("google")
pyautogui.sleep(1)
pyautogui.press("ENTER")
pyautogui.sleep(1)
pyautogui.click(694,584)
pyautogui.sleep(1)
pyautogui.write("facecebook.com")
pyautogui.sleep(1)
pyautogui.press('ENTER')
pyautogui.sleep(2)
pyautogui.write("deinha@gmail.com")
pyautogui.sleep(1)
pyautogui.press("tab")
pyautogui.sleep(1)
pyautogui.write("12345678")